PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT
    ?frId
    ?last
    ?bday
    ?since
    ?gen
    ?browser
    ?locationIP
    ?email
    ?languages
    ?based
    ?studies
    ?jobs
{
    {
        SELECT
            ?fr
            ?email
            ?language
        WHERE
        {
            {
                SELECT ?fr ?email WHERE
                {
                    {
                        SELECT ?fr WHERE
                        {
                            ?rootPerson a snvoc:Person .
                            ?rootPerson snvoc:id $personId .
                            ?fr a snvoc:Person .
                            {
                                ?rootPerson snvoc:knows/snvoc:hasPerson ?fr .
                            } 
                            UNION {
                                ?fr snvoc:knows/snvoc:hasPerson ?rootPerson .
                            } 
                            UNION
                            {
                                ?rootPerson snvoc:knows/snvoc:hasPerson/snvoc:knows/snvoc:hasPerson ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:knows/snvoc:hasPerson/snvoc:hasPerson/snvoc:knows ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:hasPerson/snvoc:knows/snvoc:knows/snvoc:hasPerson ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:hasPerson/snvoc:knows/snvoc:hasPerson/snvoc:knows ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:knows/snvoc:hasPerson/snvoc:knows/snvoc:hasPerson/snvoc:knows/snvoc:hasPerson ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:knows/snvoc:hasPerson/snvoc:knows/snvoc:hasPerson/snvoc:hasPerson/snvoc:knows ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:knows/snvoc:hasPerson/snvoc:hasPerson/snvoc:knows/snvoc:knows/snvoc:hasPerson ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:knows/snvoc:hasPerson/snvoc:hasPerson/snvoc:knows/snvoc:hasPerson/snvoc:knows ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:hasPerson/snvoc:knows/snvoc:knows/snvoc:hasPerson/snvoc:knows/snvoc:hasPerson ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:hasPerson/snvoc:knows/snvoc:knows/snvoc:hasPerson/snvoc:hasPerson/snvoc:knows ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:hasPerson/snvoc:knows/snvoc:hasPerson/snvoc:knows/snvoc:knows/snvoc:hasPerson ?fr .
                            }
                            UNION
                            {
                                ?rootPerson snvoc:hasPerson/snvoc:knows/snvoc:hasPerson/snvoc:knows/snvoc:hasPerson/snvoc:knows ?fr .
                            }
                            ?fr snvoc:id ?frId .
                            FILTER(?frId != $personId) .
                            ?fr snvoc:firstName $firstName .
                        }
                    }
                    ?fr snvoc:email ?email .
                }
            }
            ?fr snvoc:speaks ?language
        }
    }
    ?fr snvoc:id ?frId .
    ?fr snvoc:lastName ?last .
    ?fr snvoc:birthday ?bday .
    ?fr snvoc:isLocatedIn ?basedURI .
    ?basedURI foaf:name ?based .
    ?fr snvoc:creationDate ?since .
    ?fr snvoc:gender ?gen .
    ?fr snvoc:locationIP ?locationIP .
    ?fr snvoc:browserUsed ?browser .
    OPTIONAL {
        {
            SELECT
                ?frInner
                ?uniName
                ?classYear
                ?uniCountry
            {
                ?frInner a snvoc:Person .
                ?frInner snvoc:studyAt ?study .
                ?study snvoc:hasOrganisation ?uni .
                ?uni foaf:name ?uniName .
                ?study snvoc:classYear ?classYear .
                ?uni snvoc:isLocatedIn/foaf:name ?uniCountry .
            }
        } .
        ?frInner snvoc:id ?frInner .
        FILTER( ?frId = ?frInner)
    } .
    OPTIONAL {
        {
            SELECT
                ?frInner
                ?companyName
                ?workFrom
                ?companyCountry
            {
                ?frInner a snvoc:Person .
                ?frInner snvoc:workAt ?work .
                ?work snvoc:hasOrganisation ?company .
                ?work snvoc:workFrom ?workFrom .
                ?company snvoc:isLocatedIn/foaf:name ?companyCountry .
                ?company foaf:name ?companyName
            }
        } .
        ?frInner snvoc:id ?frInner .
        FILTER( ?frId = ?frInner)
    }
}